### ISSUE TITLE
what is the cpp.js file used for?

### ISSUE THREAD

**Issue by asmwarrior** [penguinfreud/cpp-preprocessor#2]
It looks like you have implement the c-preprocessor in both C++ source file and javascript file?
Thanks.

**Comment by penguinfreud** [comment]
The javascript file is a prototype of the C++ version. This project is a toy preprocessor implementation. It was the first time I ever wrote more than a hundred LoC in C++. There is no guarantee that the code follows best practices or is thoroughly tested. I do not suggest using this implementation for any serious purpose.

**Comment by asmwarrior** [comment]
Ok, thanks for the explanation. I think this issue can be closed.
